# Auto-generated by stubgen.py on Mon Jan  9 15:08:00 2017
# -- HAND EDITING NOT ADVISED ---


import InsTask

# Special module-level constant to tell task manager what default subsystem
# these tasks are for
SUBSYS = 'CHARIS'



####################################################################
# BASE CHARIS TASKS
####################################################################
#
class CHARISTaskError(InsTask.Ins2TaskError):
    pass

class CHARISTask(InsTask.Ins2Task):
    """Base CHARIS task from which CHARIS device dependent commands tasks
    are derived.
    """
    def __init__(self, cmdname, **kwdargs):
        """_cmdname_ is the command name for this task.
        """

        # This copies all keyword arguments to self.params and does
        # general task initialization
        super(CHARISTask, self).__init__('CHARIS', cmdname, **kwdargs)

    #######################################
    # CHARIS INSTRUMENT COMMANDS
    #######################################


class Filter(CHARISTask):
    def __init__(self, name=None):
        super(Filter, self).__init__('Filter', name=name)

class Fits_File(CHARISTask):
    def __init__(self, frame_no=None, target=None):
        super(Fits_File, self).__init__('Fits_File', frame_no=frame_no, target=target)

class Getstatus(CHARISTask):
    def __init__(self, target=None):
        super(Getstatus, self).__init__('Getstatus', target=target)

class Grism(CHARISTask):
    def __init__(self, pos=None):
        super(Grism, self).__init__('Grism', pos=pos)

class Obcp_Mode(CHARISTask):
    def __init__(self, motor=None, mode=None):
        super(Obcp_Mode, self).__init__('Obcp_Mode', motor=motor, mode=mode)

class Ramp(CHARISTask):
    def __init__(self, exptype=None, nreset=None, nread=None, exptime=None, objname=None):
        super(Ramp, self).__init__('Ramp', exptype=exptype, nreset=nreset, nread=nread, exptime=exptime, objname=objname)

class Setup(CHARISTask):
    def __init__(self, etime=None, data_type=None, nreset=None, nread=None):
        super(Setup, self).__init__('Setup', etime=etime, data_type=data_type, nreset=nreset, nread=nread)

class Shutter(CHARISTask):
    def __init__(self, pos=None):
        super(Shutter, self).__init__('Shutter', pos=pos)

class Sleep(CHARISTask):
    def __init__(self, sleep_time=None):
        super(Sleep, self).__init__('Sleep', sleep_time=sleep_time)

